[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]

[background]
path = "/usr/share/wallpapers/regreet_wallpaper.jpg"
fit = "Cover"

[GTK]
theme_name = "Adwaita-Dark"
icon_theme_name = "Papirus-Dark"
font_name = "JetBrainsMono Nerd Font"
application_prefer_dark_theme = true
