[General]
DisplayServer=wayland
GreeterEnviroment=QT_WAYLAND_DISABLE_WINDOWDECORATION=1,QT_QPA_PLATFORM=wayland

[Theme]
Current=glassmorphism
CursorSize=32
CursorTheme=capitaine-cursors
Font=JetBrainsMono Nerd Font

[Users]
RememberLastSession=true
RememberLastUser=true

[Wayland]
CompositorCommand=start-hyprland -- -c /etc/sddm.conf.d/hyprland.lua
