general {
    lock_cmd = pidof hyprlock || ~/.config/hypr/lock_runner.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# BLOQUEIO: Após 5 minutos de inatividade
listener {
    timeout = 300                                
    on-timeout = loginctl lock-session           
}

# comentado no momento pois não está mais funcionando como deveria
# provavelmente a combinação de nvidia com os monitores com displayport quebraram essa funcionalidade
# ECONOMIA DE ENERGIA: Desliga o monitor após 10 minutos
# listener {
#     timeout = 600                                
#     on-timeout = hyprctl dispatch dpms off       
#     on-resume = hyprctl dispatch dpms on
# }

# comentado no momento pois não funciona como o esperado
# SUSPENSÃO: Suspende o sistema após 15 minutos
# --- COMENTE AS LINHAS ABAIXO SE ESTIVER FAZENDO DOWNLOAD ---
#  listener {
#      timeout = 900                                
#      on-timeout = systemctl suspend               
#  }
